logging:
  level:
    root: info
management:
  security:
    enabled: false
server:
  port: 9005
spring:
  application:
    name: config-client-sample
  autoconfigure:
    exclude:
      - SpringApplicationAdminJmxAutoConfiguration.class

 